name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: docker build -t webjmail:${{ github.sha }} .
      
      - name: Save image
        run: docker save webjmail:${{ github.sha }} | gzip > webjmail.tar.gz
      
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "webjmail.tar.gz,docker-compose.yml"
          target: "/opt/webjmail"
      
      - name: Run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/webjmail
            docker load < webjmail.tar.gz
            docker tag webjmail:${{ github.sha }} webjmail:latest
            docker-compose up -d
            docker system prune -f
